FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit \
    altair \
    pandas \
    joblib \
    scikit-learn==1.4.2 \
    numpy \
    shap \
    openai

COPY dashboard_genai_docker.py dashboard.py

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
